
package com.mycompany.qlpcc;

import UI.*;
import QuyCoding.QuyCoding.*;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Dang_nhap extends javax.swing.JFrame {

    /**
     * Creates new form Dang_nhap
     */
    public Dang_nhap() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_Tendangnhap = new javax.swing.JLabel();
        Label_Dangnhap = new javax.swing.JLabel();
        Label_Matkhau = new javax.swing.JLabel();
        TextField_Tendangnhap = new javax.swing.JTextField();
        Button_Dangnhap = new javax.swing.JButton();
        PasswordField_Matkhau = new javax.swing.JPasswordField();
        ToggleButton_Hienthi = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Label_Tendangnhap.setText("Tên đăng nhập");

        Label_Dangnhap.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Label_Dangnhap.setText("ĐĂNG NHẬP");

        Label_Matkhau.setText("Mật khẩu");

        TextField_Tendangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_TendangnhapActionPerformed(evt);
            }
        });

        Button_Dangnhap.setText("Đăng nhập");
        Button_Dangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_DangnhapActionPerformed(evt);
            }
        });

        PasswordField_Matkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordField_MatkhauActionPerformed(evt);
            }
        });

        ToggleButton_Hienthi.setText("Hiển thị");
        ToggleButton_Hienthi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ToggleButton_HienthiMouseClicked(evt);
            }
        });
        ToggleButton_Hienthi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleButton_HienthiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_Tendangnhap)
                    .addComponent(Label_Matkhau))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_Dangnhap)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(Button_Dangnhap))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextField_Tendangnhap)
                            .addComponent(PasswordField_Matkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(ToggleButton_Hienthi, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(Label_Dangnhap)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Tendangnhap)
                    .addComponent(TextField_Tendangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Matkhau)
                    .addComponent(PasswordField_Matkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ToggleButton_Hienthi))
                .addGap(35, 35, 35)
                .addComponent(Button_Dangnhap)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_DangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_DangnhapActionPerformed
        // TODO add your handling code here:
        String user = TextField_Tendangnhap.getText().trim();
        String password = PasswordField_Matkhau.getText().trim();
        Connection ketnoi = KetNoiDB.KetNoi();
        if(user.isEmpty() || password.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nhap du thong tin");
        }
        else{
            try {
            Statement st = ketnoi.createStatement();
            String sql = "select * from DANG_NHAP where ten_dang_nhap='%s' and mat_khau='%s'";
            sql = String.format(sql, user, password);
            ResultSet rs = st.executeQuery(sql);
            if(!rs.next())
               JOptionPane.showMessageDialog(this, "Ten dang nhap hoac mat khau khong dung");
            else{
                
                String quyen = "";
               
                quyen = rs.getString("ma_quyen");
                    
                quyen = quyen.trim();
                
                if(quyen.equals("NV")){
                    //System.out.println(user);
                    new Nhan_vien(user).setVisible(true);
                    QuyCoding.QuyCoding.Nhan_vien.run_Quy();
                    setVisible(false);
                }
                else if(quyen.equals("CSH")){
                    new CHU_SO_HUU().setVisible(true);
                    
                    setVisible(false);
                }
                rs.close();
                ketnoi.close();
            }
            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Loi ket noi");
            }
        }
    }//GEN-LAST:event_Button_DangnhapActionPerformed

    private void TextField_TendangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_TendangnhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_TendangnhapActionPerformed

    private void PasswordField_MatkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordField_MatkhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordField_MatkhauActionPerformed

    private void ToggleButton_HienthiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleButton_HienthiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToggleButton_HienthiActionPerformed

    private void ToggleButton_HienthiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ToggleButton_HienthiMouseClicked
        // TODO add your handling code here:
        if(ToggleButton_Hienthi.isSelected()){
            PasswordField_Matkhau.setEchoChar((char)0);
        }
        else{
            PasswordField_Matkhau.setEchoChar('*');
        }
    }//GEN-LAST:event_ToggleButton_HienthiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dang_nhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dang_nhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dang_nhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dang_nhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dang_nhap().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Dangnhap;
    private javax.swing.JLabel Label_Dangnhap;
    private javax.swing.JLabel Label_Matkhau;
    private javax.swing.JLabel Label_Tendangnhap;
    private javax.swing.JPasswordField PasswordField_Matkhau;
    private javax.swing.JTextField TextField_Tendangnhap;
    private javax.swing.JToggleButton ToggleButton_Hienthi;
    // End of variables declaration//GEN-END:variables
}
