/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.qlpcc;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Dang_nhap extends javax.swing.JFrame {

    /**
     * Creates new form Dang_nhap
     */
    public Dang_nhap() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_Tendangnhap = new javax.swing.JLabel();
        Label_Dangnhap = new javax.swing.JLabel();
        Label_Matkhau = new javax.swing.JLabel();
        TextField_Tendangnhap = new javax.swing.JTextField();
        TextField_Matkhau = new javax.swing.JTextField();
        Button_Dangnhap = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Label_Tendangnhap.setText("Tên đăng nhập");

        Label_Dangnhap.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Label_Dangnhap.setText("ĐĂNG NHẬP");

        Label_Matkhau.setText("Mật khẩu");

        TextField_Tendangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_TendangnhapActionPerformed(evt);
            }
        });

        TextField_Matkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_MatkhauActionPerformed(evt);
            }
        });

        Button_Dangnhap.setText("Đăng nhập");
        Button_Dangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_DangnhapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_Tendangnhap)
                            .addComponent(Label_Matkhau))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextField_Matkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextField_Tendangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(Label_Dangnhap))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(Button_Dangnhap)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(Label_Dangnhap)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Tendangnhap)
                    .addComponent(TextField_Tendangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Matkhau)
                    .addComponent(TextField_Matkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(Button_Dangnhap)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_DangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_DangnhapActionPerformed
        // TODO add your handling code here:
        String user = TextField_Tendangnhap.getText();
        String password = TextField_Matkhau.getText();
        Connection ketnoi = KetNoiDB.KetNoi();
        if(user.isEmpty() || password.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nhap du thong tin");
        }
        else{
            try {
            Statement ps = ketnoi.createStatement();
            String sql = "select * from DANG_NHAP where ten_dang_nhap='%s'";
            sql = String.format(sql, user);
            ResultSet rs = ps.executeQuery(sql);
            System.out.println(rs.getString("ma_quyen"));
            rs.close();
            ketnoi.close();
            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Loi ket noi");
            }
        }
    }//GEN-LAST:event_Button_DangnhapActionPerformed

    private void TextField_TendangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_TendangnhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_TendangnhapActionPerformed

    private void TextField_MatkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_MatkhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_MatkhauActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dang_nhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dang_nhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dang_nhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dang_nhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dang_nhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Dangnhap;
    private javax.swing.JLabel Label_Dangnhap;
    private javax.swing.JLabel Label_Matkhau;
    private javax.swing.JLabel Label_Tendangnhap;
    private javax.swing.JTextField TextField_Matkhau;
    private javax.swing.JTextField TextField_Tendangnhap;
    // End of variables declaration//GEN-END:variables
}
