package com.mycompany.qlpcc;

import QuyCoding.QuyCoding.*;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 *
 * @author Admin
 */
public class Nhan_vien extends javax.swing.JFrame {
    Connection ketnoi = KetNoiDB.KetNoi();
    /**
     * Creates new form Nhan_vien
     */
    private String ma_nhan_vien;
    public Nhan_vien(String ma_nhan_vien) {
        initComponents();
        //new Dang_nhap();
        this.ma_nhan_vien = ma_nhan_vien;
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_Phai = new javax.swing.ButtonGroup();
        panel_dichvu = new javax.swing.JTabbedPane();
        Panel_Thongtin = new javax.swing.JPanel();
        Label_manhanvien = new javax.swing.JLabel();
        Label_hoten = new javax.swing.JLabel();
        Label_sdt = new javax.swing.JLabel();
        Label_cccd = new javax.swing.JLabel();
        Label_ngaysinh = new javax.swing.JLabel();
        Label_phai = new javax.swing.JLabel();
        Label_phongban = new javax.swing.JLabel();
        Label_hienmanhanvien = new javax.swing.JLabel();
        Label_hienhoten = new javax.swing.JLabel();
        Label_hiensdt = new javax.swing.JLabel();
        Label_hiencccd = new javax.swing.JLabel();
        Label_hienngaysinh = new javax.swing.JLabel();
        Label_hienphai = new javax.swing.JLabel();
        Label_tendangnhap = new javax.swing.JLabel();
        Label_hientendangnhap = new javax.swing.JLabel();
        Label_hienphongban = new javax.swing.JLabel();
        Panel_quanlytaikhoan = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Chusohuu = new javax.swing.JTable();
        Label_Tendangnhap = new javax.swing.JLabel();
        TextField_Tendangnhap = new javax.swing.JTextField();
        Label_Machusohuu = new javax.swing.JLabel();
        TextField_Machusohuu = new javax.swing.JTextField();
        Label_Hoten = new javax.swing.JLabel();
        TextField_Hoten = new javax.swing.JTextField();
        Label_Sdt = new javax.swing.JLabel();
        TextField_Sdt = new javax.swing.JTextField();
        Label_Phai = new javax.swing.JLabel();
        Label_Ngaysinh = new javax.swing.JLabel();
        TextField_Ngaysinh = new javax.swing.JTextField();
        Label_Cccd = new javax.swing.JLabel();
        TextField_Cccd = new javax.swing.JTextField();
        Label_Matkhau = new javax.swing.JLabel();
        TextField_Matkhau = new javax.swing.JTextField();
        Them = new javax.swing.JButton();
        Sua = new javax.swing.JButton();
        Xoa = new javax.swing.JButton();
        RadioButton_Nam = new javax.swing.JRadioButton();
        RadioButton_Nu = new javax.swing.JRadioButton();
        Button_Lammoi = new javax.swing.JButton();
        Panel_Thongke = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_Thongke = new javax.swing.JTable();
        TextField_Tim = new javax.swing.JTextField();
        Button_Tim = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ComboBox_Canho = new javax.swing.JComboBox<>();
        Button_Dangxuat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_dichvu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        Panel_Thongtin.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                Panel_ThongtinAncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        Panel_Thongtin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_ThongtinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Panel_ThongtinMouseEntered(evt);
            }
        });

        Label_manhanvien.setText("Mã nhân viên");

        Label_hoten.setText("Họ và tên");

        Label_sdt.setText("SĐT");

        Label_cccd.setText("CCCD");

        Label_ngaysinh.setText("Ngày sinh");

        Label_phai.setText("Phái");

        Label_phongban.setText("Phòng ban");

        Label_tendangnhap.setText("Tên đăng nhập");

        javax.swing.GroupLayout Panel_ThongtinLayout = new javax.swing.GroupLayout(Panel_Thongtin);
        Panel_Thongtin.setLayout(Panel_ThongtinLayout);
        Panel_ThongtinLayout.setHorizontalGroup(
            Panel_ThongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ThongtinLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(Panel_ThongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_ThongtinLayout.createSequentialGroup()
                        .addComponent(Label_tendangnhap)
                        .addGap(24, 24, 24))
                    .addGroup(Panel_ThongtinLayout.createSequentialGroup()
                        .addGroup(Panel_ThongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Label_phai, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_cccd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_hoten)
                            .addComponent(Label_manhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Label_ngaysinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Label_phongban, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31)))
                .addGroup(Panel_ThongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Label_hientendangnhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label_hienmanhanvien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label_hienhoten, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label_hiensdt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label_hiencccd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label_hienngaysinh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label_hienphai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(Label_hienphongban, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_ThongtinLayout.setVerticalGroup(
            Panel_ThongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ThongtinLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Panel_ThongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_tendangnhap)
                    .addComponent(Label_hientendangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel_ThongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_manhanvien)
                    .addComponent(Label_hienmanhanvien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_ThongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_hoten)
                    .addComponent(Label_hienhoten))
                .addGap(12, 12, 12)
                .addGroup(Panel_ThongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_sdt)
                    .addComponent(Label_hiensdt))
                .addGap(12, 12, 12)
                .addGroup(Panel_ThongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_cccd)
                    .addComponent(Label_hiencccd))
                .addGap(12, 12, 12)
                .addGroup(Panel_ThongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_ngaysinh)
                    .addComponent(Label_hienngaysinh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_ThongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_phai)
                    .addComponent(Label_hienphai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_ThongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_phongban)
                    .addComponent(Label_hienphongban))
                .addGap(73, 73, 73))
        );

        panel_dichvu.addTab("Thông tin", Panel_Thongtin);

        Panel_quanlytaikhoan.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                Panel_quanlytaikhoanAncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        Table_Chusohuu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Tên đăng nhập", "Mã chủ sở hữu", "Họ và tên", "SĐT", "Phái", "Ngày sinh", "CCCD"
            }
        ));
        Table_Chusohuu.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                Table_ChusohuuAncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        Table_Chusohuu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_ChusohuuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table_Chusohuu);

        Label_Tendangnhap.setText("Tên đăng nhập");

        TextField_Tendangnhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextField_TendangnhapMouseClicked(evt);
            }
        });
        TextField_Tendangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_TendangnhapActionPerformed(evt);
            }
        });

        Label_Machusohuu.setText("Mã chủ sở hữu");

        TextField_Machusohuu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextField_MachusohuuMouseClicked(evt);
            }
        });
        TextField_Machusohuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_MachusohuuActionPerformed(evt);
            }
        });

        Label_Hoten.setText("Họ và tên");

        Label_Sdt.setText("SĐT");

        Label_Phai.setText("Phái");

        Label_Ngaysinh.setText("Ngày sinh");

        Label_Cccd.setText("CCCD");

        Label_Matkhau.setText("Mật khẩu");

        Them.setText("Thêm");
        Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemActionPerformed(evt);
            }
        });

        Sua.setText("Sửa");
        Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuaActionPerformed(evt);
            }
        });

        Xoa.setText("Xóa");
        Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoaActionPerformed(evt);
            }
        });

        buttonGroup_Phai.add(RadioButton_Nam);
        RadioButton_Nam.setText("NAM");

        buttonGroup_Phai.add(RadioButton_Nu);
        RadioButton_Nu.setText("NU");

        Button_Lammoi.setText("Làm mới");
        Button_Lammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_LammoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_quanlytaikhoanLayout = new javax.swing.GroupLayout(Panel_quanlytaikhoan);
        Panel_quanlytaikhoan.setLayout(Panel_quanlytaikhoanLayout);
        Panel_quanlytaikhoanLayout.setHorizontalGroup(
            Panel_quanlytaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_quanlytaikhoanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(Panel_quanlytaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_quanlytaikhoanLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel_quanlytaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_quanlytaikhoanLayout.createSequentialGroup()
                                .addComponent(Label_Tendangnhap)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextField_Tendangnhap))
                            .addGroup(Panel_quanlytaikhoanLayout.createSequentialGroup()
                                .addGroup(Panel_quanlytaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label_Machusohuu)
                                    .addComponent(Label_Hoten)
                                    .addComponent(Label_Sdt)
                                    .addComponent(Label_Phai)
                                    .addComponent(Label_Ngaysinh)
                                    .addComponent(Label_Cccd)
                                    .addComponent(Label_Matkhau))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Panel_quanlytaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextField_Matkhau)
                                    .addComponent(TextField_Cccd)
                                    .addComponent(TextField_Ngaysinh)
                                    .addComponent(TextField_Sdt)
                                    .addComponent(TextField_Hoten)
                                    .addComponent(TextField_Machusohuu)
                                    .addGroup(Panel_quanlytaikhoanLayout.createSequentialGroup()
                                        .addComponent(RadioButton_Nam, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(RadioButton_Nu, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(Panel_quanlytaikhoanLayout.createSequentialGroup()
                                .addComponent(Them, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 101, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_quanlytaikhoanLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Button_Lammoi, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))))
        );
        Panel_quanlytaikhoanLayout.setVerticalGroup(
            Panel_quanlytaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_quanlytaikhoanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Panel_quanlytaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_quanlytaikhoanLayout.createSequentialGroup()
                        .addGroup(Panel_quanlytaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_Tendangnhap)
                            .addComponent(TextField_Tendangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel_quanlytaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_Machusohuu)
                            .addComponent(TextField_Machusohuu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel_quanlytaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_Hoten)
                            .addComponent(TextField_Hoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel_quanlytaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_Sdt)
                            .addComponent(TextField_Sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel_quanlytaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_Phai)
                            .addComponent(RadioButton_Nam)
                            .addComponent(RadioButton_Nu))
                        .addGap(9, 9, 9)
                        .addGroup(Panel_quanlytaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_Ngaysinh)
                            .addComponent(TextField_Ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel_quanlytaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_Cccd)
                            .addComponent(TextField_Cccd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel_quanlytaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_Matkhau)
                            .addComponent(TextField_Matkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Panel_quanlytaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Them)
                            .addComponent(Sua)
                            .addComponent(Xoa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Button_Lammoi))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panel_dichvu.addTab("Quản lý tài khoản", Panel_quanlytaikhoan);

        Panel_Thongke.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                Panel_ThongkeAncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        Table_Thongke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên hóa đơn", "Căn hộ", "Người lập hóa đơn", "Tổng tiền"
            }
        ));
        jScrollPane2.setViewportView(Table_Thongke);

        Button_Tim.setText("Tìm");

        jLabel1.setText("Tên hóa đơn");

        jLabel2.setText("Căn hộ");

        ComboBox_Canho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_CanhoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_ThongkeLayout = new javax.swing.GroupLayout(Panel_Thongke);
        Panel_Thongke.setLayout(Panel_ThongkeLayout);
        Panel_ThongkeLayout.setHorizontalGroup(
            Panel_ThongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ThongkeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_ThongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_ThongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_ThongkeLayout.createSequentialGroup()
                        .addComponent(TextField_Tim, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(Button_Tim, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_ThongkeLayout.createSequentialGroup()
                        .addComponent(ComboBox_Canho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Panel_ThongkeLayout.setVerticalGroup(
            Panel_ThongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ThongkeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_ThongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_ThongkeLayout.createSequentialGroup()
                        .addGroup(Panel_ThongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextField_Tim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button_Tim)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel_ThongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(ComboBox_Canho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_dichvu.addTab("Thống kê", Panel_Thongke);

        Button_Dangxuat.setText("Đăng xuất");
        Button_Dangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_DangxuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Button_Dangxuat)
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_dichvu)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Button_Dangxuat)
                .addGap(18, 18, 18)
                .addComponent(panel_dichvu))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_DangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_DangxuatActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Dang_nhap().setVisible(true);
    }//GEN-LAST:event_Button_DangxuatActionPerformed

    private void Panel_ThongtinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_ThongtinMouseEntered
       
        // TODO add your handling code here:
        //Label_hienmanhanvien.setText(ma_nhan_vien);
    }//GEN-LAST:event_Panel_ThongtinMouseEntered

    private void Panel_ThongtinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_ThongtinMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Panel_ThongtinMouseClicked

    private void Panel_ThongtinAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_Panel_ThongtinAncestorMoved
        // TODO add your handling code here:
        Label_hientendangnhap.setText(ma_nhan_vien);
        //Connection ketnoi = KetNoiDB.KetNoi();
        try {
            Statement st = ketnoi.createStatement();
            String sql = "select * from NHAN_VIEN where ten_dang_nhap='%s'";
            sql = String.format(sql, ma_nhan_vien);
            ResultSet rs = st.executeQuery(sql);
            if(!rs.next())
                JOptionPane.showMessageDialog(this, "Khong tim thay");
            else{
                String ma_nhan_vien = rs.getString("ma_nhan_vien").trim();
                String ho_ten = rs.getString("ho_ten").trim();
                String sdt = rs.getString("sdt").trim();
                String cccd = rs.getString("cccd").trim();
                String ngay_sinh = rs.getString("ngay_sinh").trim();
                String phai = rs.getString("phai").trim();
                String ma_phong_ban = rs.getString("ma_phong_ban").trim();
            
                sql = "select * from PHONG_BAN where ma_phong_ban='%s'";
                sql = String.format(sql, ma_phong_ban);
                ResultSet rs1 = st.executeQuery(sql);

                if(rs1.next()){
                    String phong_ban = rs1.getString("ten_phong_ban").trim();
                    Label_hienmanhanvien.setText(ma_nhan_vien);
                    Label_hienhoten.setText(ho_ten);
                    Label_hiensdt.setText(sdt);
                    Label_hiencccd.setText(cccd);
                    Label_hienngaysinh.setText(ngay_sinh);
                    Label_hienphai.setText(phai);
                    Label_hienphongban.setText(phong_ban);
                }
            }
            
            rs.close();
            //ketnoi.close();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Loi ket noi");
        }
    }//GEN-LAST:event_Panel_ThongtinAncestorMoved

    private void SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuaActionPerformed
        // TODO add your handling code here:
        //Connection ketnoi = KetNoiDB.KetNoi();
        try {
            Statement st = ketnoi.createStatement();
            String ten_dang_nhap = TextField_Tendangnhap.getText();
            String ma_chu_so_huu = TextField_Machusohuu.getText();
//            TextField_Machusohuu.setEditable(false);
//            TextField_Tendangnhap.setEditable(false);
            String ho_ten = TextField_Hoten.getText();
            String sdt = TextField_Sdt.getText();
            String phai = "";
            if(RadioButton_Nam.isSelected())
                phai = "NAM";
            else
                phai = "NU";
            String ngay_sinh = TextField_Ngaysinh.getText();
            String cccd = TextField_Cccd.getText();
            String mat_khau = TextField_Matkhau.getText();
            if(ho_ten.isEmpty() || sdt.isEmpty() || phai.isEmpty() || ngay_sinh.isEmpty() || cccd.isEmpty() || mat_khau.isEmpty())
                JOptionPane.showMessageDialog(this, "Nhap du thong tin");
            else{
               String sql = "update DANG_NHAP set mat_khau='%s' where ten_dang_nhap='%s'";
               sql = String.format(sql, mat_khau, ten_dang_nhap);
               st.executeUpdate(sql);
                
               sql = "update CHU_SO_HUU set ho_ten='%s', sdt='%s', phai='%s', ngay_sinh='%s', cccd='%s' where ma_chu_so_huu='%s'";
               sql = String.format(sql, ho_ten, sdt, phai, ngay_sinh, cccd, ma_chu_so_huu);
               st.executeUpdate(sql);
               
               DefaultTableModel table = (DefaultTableModel) Table_Chusohuu.getModel();
               table.setRowCount(0);
               in_csh();
               
               st.close();
               //ketnoi.close();
            }
            
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Loi ket noi");
        }
    }//GEN-LAST:event_SuaActionPerformed

    private void Table_ChusohuuAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_Table_ChusohuuAncestorMoved
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Table_ChusohuuAncestorMoved

    private void Panel_quanlytaikhoanAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_Panel_quanlytaikhoanAncestorMoved
        // TODO add your handling code here:
        in_csh();
    }//GEN-LAST:event_Panel_quanlytaikhoanAncestorMoved

    private void Table_ChusohuuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_ChusohuuMouseClicked
        // TODO add your handling code here:
       //Connection ketnoi = KetNoiDB.KetNoi();
       
        try {
            int row = -1;
            row = Table_Chusohuu.getSelectedRow();
            if(row != -1){
                Statement st = ketnoi.createStatement();
                String ten_dang_nhap = Table_Chusohuu.getModel().getValueAt(row, 0).toString().trim();
                String ma_chu_so_huu = Table_Chusohuu.getModel().getValueAt(row, 1).toString().trim();
                String ho_ten = Table_Chusohuu.getModel().getValueAt(row, 2).toString().trim();
                String sdt = Table_Chusohuu.getModel().getValueAt(row, 3).toString().trim();
                String phai = Table_Chusohuu.getModel().getValueAt(row, 4).toString().trim();
                String ngay_sinh = Table_Chusohuu.getModel().getValueAt(row, 5).toString().trim();
                String cccd = Table_Chusohuu.getModel().getValueAt(row, 6).toString().trim();
                
                String sql = "select mat_khau from DANG_NHAP where ten_dang_nhap='%s'";
                
                sql = String.format(sql, ten_dang_nhap);
                
                ResultSet rs = st.executeQuery(sql);
                
                String mat_khau = "";
                if(rs.next()){
                    mat_khau = rs.getString("mat_khau").trim();
                    rs.close();
                    //ketnoi.close();
                }
                
                TextField_Tendangnhap.setText(ten_dang_nhap);
                TextField_Machusohuu.setText(ma_chu_so_huu);
                TextField_Hoten.setText(ho_ten);
                TextField_Sdt.setText(sdt);
                if(phai.equals("NAM")){
                    RadioButton_Nam.setSelected(true);
                    RadioButton_Nu.setSelected(false);
                }
                else if(phai.equals("NU")){
                    RadioButton_Nam.setSelected(false);
                    RadioButton_Nu.setSelected(true);
                }
                TextField_Ngaysinh.setText(ngay_sinh);
                TextField_Cccd.setText(cccd);
                TextField_Matkhau.setText(mat_khau);
                
                
            }
            
            
            
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Loi ket noi");
        }
    }//GEN-LAST:event_Table_ChusohuuMouseClicked

    private void ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemActionPerformed
        // TODO add your handling code here:
        String ten_dang_nhap = TextField_Tendangnhap.getText();
        String ma_chu_so_huu = TextField_Machusohuu.getText();
//        TextField_Machusohuu.setEditable(true);
//        TextField_Tendangnhap.setEditable(true);
        
        String ho_ten = TextField_Hoten.getText();
        String sdt = TextField_Sdt.getText();
        String phai = "";
        if(RadioButton_Nam.isSelected())
            phai = "NAM";
        else
            phai = "NU";
        String ngay_sinh = TextField_Ngaysinh.getText();
        String cccd = TextField_Cccd.getText();
        String mat_khau = TextField_Matkhau.getText();
        
        if(ten_dang_nhap.isEmpty() || ma_chu_so_huu.isEmpty() || ho_ten.isEmpty() || sdt.isEmpty() || phai.isEmpty() || ngay_sinh.isEmpty() || cccd.isEmpty() || mat_khau.isEmpty())
            JOptionPane.showMessageDialog(this, "Nhap du thong tin");
        else{
            //Connection ketnoi = KetNoiDB.KetNoi();
            try {
               
                Statement st = ketnoi.createStatement();
                String sql = "insert into DANG_NHAP (ten_dang_nhap, mat_khau, ma_quyen) "
                        + "values ('%s', '%s', 'CSH')";
                sql = String.format(sql, ten_dang_nhap, mat_khau);
                st.executeUpdate(sql);
                
                sql = "insert into CHU_SO_HUU (ma_chu_so_huu, ho_ten, sdt, phai, ngay_sinh, cccd, ten_dang_nhap) " 
                        + "values ('%s', '%s', '%s', '%s', '%s', '%s', '%s')";
                sql = String.format(sql, ma_chu_so_huu, ho_ten, sdt, phai, ngay_sinh, cccd, ten_dang_nhap);
                st.executeUpdate(sql);
                
               
                
                DefaultTableModel table = (DefaultTableModel)Table_Chusohuu.getModel();
                table.setRowCount(0);
                TextField_Machusohuu.setEditable(false);
                TextField_Tendangnhap.setEditable(false);
                in_csh();
                st.close();
                //ketnoi.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_ThemActionPerformed

    private void TextField_TendangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_TendangnhapActionPerformed
        // TODO add your handling code here:
        String ten_dang_nhap = TextField_Tendangnhap.getText();
        if(ten_dang_nhap.isEmpty())
            TextField_Tendangnhap.setEditable(true);
        else
            TextField_Tendangnhap.setEditable(false);
    }//GEN-LAST:event_TextField_TendangnhapActionPerformed

    private void Button_LammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_LammoiActionPerformed
        // TODO add your handling code here:
        String ten_dang_nhap = TextField_Tendangnhap.getText();
        String ma_chu_so_huu = TextField_Machusohuu.getText();
        String ho_ten = TextField_Hoten.getText();
        String sdt = TextField_Sdt.getText();
        String phai = "";
        if(RadioButton_Nam.isSelected())
            phai = "NAM";
        else
            phai = "NU";
        String ngay_sinh = TextField_Ngaysinh.getText();
        String cccd = TextField_Cccd.getText();
        String mat_khau = TextField_Matkhau.getText();
        
        ten_dang_nhap = ma_chu_so_huu = ho_ten = sdt = ngay_sinh = cccd = mat_khau = "";
        TextField_Tendangnhap.setText(ten_dang_nhap);
        TextField_Machusohuu.setText(ma_chu_so_huu);
        TextField_Hoten.setText(ho_ten);
        TextField_Sdt.setText(sdt);
        buttonGroup_Phai.clearSelection();
        TextField_Ngaysinh.setText(ngay_sinh);
        TextField_Cccd.setText(cccd);
        TextField_Matkhau.setText(mat_khau);        
        
    }//GEN-LAST:event_Button_LammoiActionPerformed

    private void TextField_MachusohuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_MachusohuuActionPerformed
        // TODO add your handling code here:
        String ma_chu_so_huu = TextField_Machusohuu.getText();
        if(ma_chu_so_huu.isEmpty())
            TextField_Machusohuu.setEditable(true);
        else
            TextField_Machusohuu.setEditable(false);
    }//GEN-LAST:event_TextField_MachusohuuActionPerformed

    private void TextField_TendangnhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextField_TendangnhapMouseClicked
        // TODO add your handling code here:
        String ten_dang_nhap = TextField_Tendangnhap.getText();
        if(ten_dang_nhap.isEmpty())
            TextField_Tendangnhap.setEditable(true);
        else
            TextField_Tendangnhap.setEditable(false);
    }//GEN-LAST:event_TextField_TendangnhapMouseClicked

    private void TextField_MachusohuuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextField_MachusohuuMouseClicked
        // TODO add your handling code here:
        String ma_chu_so_huu = TextField_Machusohuu.getText();
        if(ma_chu_so_huu.isEmpty())
            TextField_Machusohuu.setEditable(true);
        else
            TextField_Machusohuu.setEditable(false);
    }//GEN-LAST:event_TextField_MachusohuuMouseClicked

    private void XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoaActionPerformed
        // TODO add your handling code here:
        
        //Connection ketnoi = KetNoiDB.KetNoi();
        try {
            Statement st = ketnoi.createStatement();
            String ma_chu_so_huu = TextField_Machusohuu.getText();
            String ten_dang_nhap = TextField_Tendangnhap.getText();
            
            String sql = "update CAN_HO set ma_chu_so_huu=NULL where ma_chu_so_huu='%s'";
            sql = String.format(sql, ma_chu_so_huu);
            st.executeUpdate(sql);
            
            sql = "delete from CHU_SO_HUU where ma_chu_so_huu='%s'";
            sql = String.format(sql, ma_chu_so_huu);
            st.executeUpdate(sql);
            
            
            
            sql = "delete from DANG_NHAP where ten_dang_nhap='%s'";
            sql = String.format(sql, ten_dang_nhap);
            st.executeUpdate(sql);
            
            
            
            DefaultTableModel table = (DefaultTableModel) Table_Chusohuu.getModel();
            table.setRowCount(0);
            in_csh(); 
           
            st.close();
            //ketnoi.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
            
    }//GEN-LAST:event_XoaActionPerformed

    private void ComboBox_CanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_CanhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox_CanhoActionPerformed

    private void Panel_ThongkeAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_Panel_ThongkeAncestorMoved
        // TODO add your handling code here:
        //Connection ketnoi = KetNoiDB.KetNoi();
        try {
            Statement st = ketnoi.createStatement();
            Vector can_ho = null;
            String sql = "select ma_can_ho from CAN_HO";
            ResultSet rs = st.executeQuery(sql);
            String s = "";
            while(rs.next()){
                s = rs.getString("ma_can_ho");
                ComboBox_Canho.addItem(s);
            }
            
            DefaultTableModel table = (DefaultTableModel) Table_Thongke.getModel();
            table.setRowCount(0);
            sql = "select * from HOA_DON";
            rs = st.executeQuery(sql);
            
            Vector v1 = null;
            
            while(rs.next()){
                v1 = new Vector();
                System.out.println(rs.getString("ten_hoa_don"));
                v1.add(rs.getString("ten_hoa_don"));
                v1.add(rs.getString("ma_can_ho"));
                v1.add(rs.getString("ma_nhan_vien"));
                v1.add(rs.getString("tien_thang"));
                
                table.addRow(v1);
            }
            
            st.close();
            //ketnoi.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_Panel_ThongkeAncestorMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[], String ma_nhan_vien) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nhan_vien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nhan_vien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nhan_vien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nhan_vien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nhan_vien(ma_nhan_vien).setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Dangxuat;
    private javax.swing.JButton Button_Lammoi;
    private javax.swing.JButton Button_Tim;
    private javax.swing.JComboBox<String> ComboBox_Canho;
    private javax.swing.JLabel Label_Cccd;
    private javax.swing.JLabel Label_Hoten;
    private javax.swing.JLabel Label_Machusohuu;
    private javax.swing.JLabel Label_Matkhau;
    private javax.swing.JLabel Label_Ngaysinh;
    private javax.swing.JLabel Label_Phai;
    private javax.swing.JLabel Label_Sdt;
    private javax.swing.JLabel Label_Tendangnhap;
    private javax.swing.JLabel Label_cccd;
    private javax.swing.JLabel Label_hiencccd;
    private javax.swing.JLabel Label_hienhoten;
    private javax.swing.JLabel Label_hienmanhanvien;
    private javax.swing.JLabel Label_hienngaysinh;
    private javax.swing.JLabel Label_hienphai;
    private javax.swing.JLabel Label_hienphongban;
    private javax.swing.JLabel Label_hiensdt;
    private javax.swing.JLabel Label_hientendangnhap;
    private javax.swing.JLabel Label_hoten;
    private javax.swing.JLabel Label_manhanvien;
    private javax.swing.JLabel Label_ngaysinh;
    private javax.swing.JLabel Label_phai;
    private javax.swing.JLabel Label_phongban;
    private javax.swing.JLabel Label_sdt;
    private javax.swing.JLabel Label_tendangnhap;
    private javax.swing.JPanel Panel_Thongke;
    private javax.swing.JPanel Panel_Thongtin;
    private javax.swing.JPanel Panel_quanlytaikhoan;
    private javax.swing.JRadioButton RadioButton_Nam;
    private javax.swing.JRadioButton RadioButton_Nu;
    private javax.swing.JButton Sua;
    private javax.swing.JTable Table_Chusohuu;
    private javax.swing.JTable Table_Thongke;
    private javax.swing.JTextField TextField_Cccd;
    private javax.swing.JTextField TextField_Hoten;
    private javax.swing.JTextField TextField_Machusohuu;
    private javax.swing.JTextField TextField_Matkhau;
    private javax.swing.JTextField TextField_Ngaysinh;
    private javax.swing.JTextField TextField_Sdt;
    private javax.swing.JTextField TextField_Tendangnhap;
    private javax.swing.JTextField TextField_Tim;
    private javax.swing.JButton Them;
    private javax.swing.JButton Xoa;
    private javax.swing.ButtonGroup buttonGroup_Phai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane panel_dichvu;
    // End of variables declaration//GEN-END:variables
    
    public void in_csh(){
        //Connection ketnoi = KetNoiDB.KetNoi();
        DefaultTableModel table = (DefaultTableModel) Table_Chusohuu.getModel();
        table.setRowCount(0);
        try {
            Statement st = ketnoi.createStatement();
            String sql = "select * from CHU_SO_HUU";
            ResultSet rs = st.executeQuery(sql);
            Vector v = null;
            while(rs.next()){
                v = new Vector();
                
                v.add(rs.getString("ten_dang_nhap"));
                v.add(rs.getString("ma_chu_so_huu"));
                v.add(rs.getString("ho_ten"));
                v.add(rs.getString("sdt"));
                v.add(rs.getString("phai"));
                v.add(rs.getString("ngay_sinh"));
               
                v.add(rs.getString("cccd"));
                
                
                table.addRow(v);
            }
            st.close();
            //ketnoi.close();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Loi ket noi");
        }
    }
    
    
    
    
}
