/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Object.*;
import java.awt.HeadlessException;
import java.nio.file.Files;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.format.DecimalStyle;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableModel;

/**
 *
 * @author minhn
 */
public class CHU_SO_HUU extends javax.swing.JFrame {
    Connection con = Database.ConnectionConfiguration.getConnection();
    /**
     * Creates new form CHU_SO_HUU
     */
    public CHU_SO_HUU() {
        initComponents();
        TTCanHo();
        TTDichVu();
        TTHoaDon();
        TTLichSuThuPhi();
        TTCuDan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabelCSH = new javax.swing.JLabel();
        jTabbedPaneMenuCSH = new javax.swing.JTabbedPane();
        jPanelTTCanHo = new javax.swing.JPanel();
        jLabelMaCanHo = new javax.swing.JLabel();
        jLabelChu = new javax.swing.JLabel();
        jLabelDienTich = new javax.swing.JLabel();
        jLabelKhu = new javax.swing.JLabel();
        jLabelTang = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTTCanHo = new javax.swing.JTable();
        jLabelDataMaCH = new javax.swing.JLabel();
        jLabelDataCSH = new javax.swing.JLabel();
        jLabelDataDienTich = new javax.swing.JLabel();
        jLabelDataKhu = new javax.swing.JLabel();
        jLabelDataTang = new javax.swing.JLabel();
        jPanelDangKiDichVu = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableTTDichVu = new javax.swing.JTable();
        jLabelTTDichVu = new javax.swing.JLabel();
        jLabelTTDangKi = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableDichVuDaChon = new javax.swing.JTable();
        jButtonXoaTatCa = new javax.swing.JButton();
        jButtonDangKi = new javax.swing.JButton();
        jButtonXoa = new javax.swing.JButton();
        jButtonThem = new javax.swing.JButton();
        jPanelHoaDon = new javax.swing.JPanel();
        jPanelContainerHoaDonChuaThanhToan = new javax.swing.JPanel();
        jLabelTenHoaDon = new javax.swing.JLabel();
        jLabelTenKhachHang = new javax.swing.JLabel();
        jLabelCanHo = new javax.swing.JLabel();
        jLabelNgayLap = new javax.swing.JLabel();
        jLabelNgayGui = new javax.swing.JLabel();
        jLabelMaTT = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTableHoaDon = new javax.swing.JTable();
        jLabelDuNo = new javax.swing.JLabel();
        jLabelSoTienPhaiDong = new javax.swing.JLabel();
        jLabelTongTien = new javax.swing.JLabel();
        jLabelTinhTrang = new javax.swing.JLabel();
        jLabelGhiChu = new javax.swing.JLabel();
        jButtonThanhToan = new javax.swing.JButton();
        jLabelDataDuNo = new javax.swing.JLabel();
        jLabelDataSoTien = new javax.swing.JLabel();
        jLabelDataTongTien = new javax.swing.JLabel();
        jLabelDataTinhTrang = new javax.swing.JLabel();
        jLabelDataGhiChu = new javax.swing.JLabel();
        jLabelDataNgayLapHD = new javax.swing.JLabel();
        jLabelDataCH = new javax.swing.JLabel();
        jLabelDataTenKH = new javax.swing.JLabel();
        jLabelDataNgayGui = new javax.swing.JLabel();
        jLabelDataThanhToan = new javax.swing.JLabel();
        jComboBoxCanHoHD = new javax.swing.JComboBox<>();
        jPanelLichSuThuPhi = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableLichSuThuPhi = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelMaCSH = new javax.swing.JLabel();
        jLabelHoTen = new javax.swing.JLabel();
        jLabelSDT = new javax.swing.JLabel();
        jLabelPhai = new javax.swing.JLabel();
        jLabelNgaySinh = new javax.swing.JLabel();
        jLabelCCCD = new javax.swing.JLabel();
        jLabelDataMaCSH = new javax.swing.JLabel();
        jLabelDataSDT = new javax.swing.JLabel();
        jLabelDataPhai = new javax.swing.JLabel();
        jLabelDataNgaysinh = new javax.swing.JLabel();
        jLabelDataCCCD = new javax.swing.JLabel();
        jLabelDataHoten = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã dịch vụ", "Tên dịch vụ", "Thuế ", "Đơn giá", "Đơn vị"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã dịch vụ", "Tên dịch vụ", "Thuế ", "Đơn giá", "Đơn vị"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelCSH.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelCSH.setText("CHỦ SỞ HỮU");

        jLabelMaCanHo.setText("Mã căn hộ:");

        jLabelChu.setText("Chủ sở hữu:");

        jLabelDienTich.setText("Diện tích:");

        jLabelKhu.setText("Khu:");

        jLabelTang.setText("Tầng: ");

        jTableTTCanHo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Căn Hộ", "Chủ sở hữu", "Diện Tích ", "Khu ", "Tầng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableTTCanHo);

        jLabelDataMaCH.setText("jLabel1");

        jLabelDataCSH.setText("jLabel1");

        jLabelDataDienTich.setText("jLabel1");

        jLabelDataKhu.setText("jLabel1");

        jLabelDataTang.setText("jLabel1");

        javax.swing.GroupLayout jPanelTTCanHoLayout = new javax.swing.GroupLayout(jPanelTTCanHo);
        jPanelTTCanHo.setLayout(jPanelTTCanHoLayout);
        jPanelTTCanHoLayout.setHorizontalGroup(
            jPanelTTCanHoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTTCanHoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanelTTCanHoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 809, Short.MAX_VALUE)
                    .addGroup(jPanelTTCanHoLayout.createSequentialGroup()
                        .addGroup(jPanelTTCanHoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelChu)
                            .addComponent(jLabelMaCanHo)
                            .addComponent(jLabelDienTich)
                            .addComponent(jLabelTang, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelKhu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(jPanelTTCanHoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelDataMaCH, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(jLabelDataCSH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelDataDienTich, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelDataKhu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelDataTang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelTTCanHoLayout.setVerticalGroup(
            jPanelTTCanHoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTTCanHoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanelTTCanHoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMaCanHo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDataMaCH))
                .addGap(24, 24, 24)
                .addGroup(jPanelTTCanHoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelChu)
                    .addComponent(jLabelDataCSH))
                .addGap(24, 24, 24)
                .addGroup(jPanelTTCanHoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDienTich, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDataDienTich))
                .addGap(24, 24, 24)
                .addGroup(jPanelTTCanHoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelKhu)
                    .addComponent(jLabelDataKhu))
                .addGap(24, 24, 24)
                .addGroup(jPanelTTCanHoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTang)
                    .addComponent(jLabelDataTang))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(232, Short.MAX_VALUE))
        );

        jTabbedPaneMenuCSH.addTab("Thông tin căn hộ", jPanelTTCanHo);

        jTableTTDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã dịch vụ", "Tên dịch vụ", "Thuế ", "Đơn giá", "Đơn vị"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTTDichVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTTDichVuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableTTDichVu);
        if (jTableTTDichVu.getColumnModel().getColumnCount() > 0) {
            jTableTTDichVu.getColumnModel().getColumn(0).setPreferredWidth(80);
            jTableTTDichVu.getColumnModel().getColumn(1).setPreferredWidth(250);
        }

        jLabelTTDichVu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTTDichVu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTTDichVu.setText("Thông tin dịch vụ");

        jLabelTTDangKi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTTDangKi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTTDangKi.setText("Dịch vụ đã chọn");

        jTableDichVuDaChon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã dịch vụ", "Tên dịch vụ", "Thuế ", "Đơn giá", "Đơn vị", "Số lượng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTableDichVuDaChon);
        if (jTableDichVuDaChon.getColumnModel().getColumnCount() > 0) {
            jTableDichVuDaChon.getColumnModel().getColumn(5).setCellEditor(null);
        }

        jButtonXoaTatCa.setText("Xóa tất cả");
        jButtonXoaTatCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXoaTatCaActionPerformed(evt);
            }
        });

        jButtonDangKi.setText("Đăng Kí");
        jButtonDangKi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDangKiActionPerformed(evt);
            }
        });

        jButtonXoa.setText("Xóa");
        jButtonXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXoaActionPerformed(evt);
            }
        });

        jButtonThem.setText("Thêm");
        jButtonThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDangKiDichVuLayout = new javax.swing.GroupLayout(jPanelDangKiDichVu);
        jPanelDangKiDichVu.setLayout(jPanelDangKiDichVuLayout);
        jPanelDangKiDichVuLayout.setHorizontalGroup(
            jPanelDangKiDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDangKiDichVuLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(jPanelDangKiDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTTDangKi)
                    .addComponent(jLabelTTDichVu))
                .addContainerGap(580, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDangKiDichVuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonThem)
                .addGap(130, 130, 130))
            .addGroup(jPanelDangKiDichVuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDangKiDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDangKiDichVuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonXoa)
                        .addGap(90, 90, 90)
                        .addComponent(jButtonXoaTatCa)
                        .addGap(90, 90, 90)
                        .addComponent(jButtonDangKi)
                        .addGap(130, 130, 130))))
        );
        jPanelDangKiDichVuLayout.setVerticalGroup(
            jPanelDangKiDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDangKiDichVuLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabelTTDichVu)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonThem)
                .addGap(9, 9, 9)
                .addComponent(jLabelTTDangKi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(jPanelDangKiDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonXoaTatCa)
                    .addComponent(jButtonDangKi)
                    .addComponent(jButtonXoa))
                .addContainerGap(166, Short.MAX_VALUE))
        );

        jTabbedPaneMenuCSH.addTab("Đăng kí dịch vụ", jPanelDangKiDichVu);

        jLabelTenHoaDon.setText("Hóa đơn tháng ....");

        jLabelTenKhachHang.setText("Tên khách hàng:");

        jLabelCanHo.setText("Căn hộ: ");

        jLabelNgayLap.setText("Ngày lập hóa đơn:");

        jLabelNgayGui.setText("Ngày gửi:");

        jLabelMaTT.setText("Mã thanh toán:");

        jTableHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên dịch vụ", "Ngày bắt đầu", "Ngày kết thúc", "Số lượng", "Đơn giá", "Đơn vị", "Thuế (%)", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(jTableHoaDon);
        if (jTableHoaDon.getColumnModel().getColumnCount() > 0) {
            jTableHoaDon.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTableHoaDon.getColumnModel().getColumn(1).setPreferredWidth(150);
            jTableHoaDon.getColumnModel().getColumn(2).setPreferredWidth(80);
            jTableHoaDon.getColumnModel().getColumn(3).setPreferredWidth(70);
            jTableHoaDon.getColumnModel().getColumn(4).setPreferredWidth(50);
            jTableHoaDon.getColumnModel().getColumn(5).setPreferredWidth(40);
            jTableHoaDon.getColumnModel().getColumn(6).setPreferredWidth(70);
            jTableHoaDon.getColumnModel().getColumn(7).setPreferredWidth(50);
        }

        jLabelDuNo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelDuNo.setText("DƯ NỢ:");

        jLabelSoTienPhaiDong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelSoTienPhaiDong.setText("SÔ TIỀN PHẢI ĐÓNG:");

        jLabelTongTien.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelTongTien.setText("TỔNG TIỀN:");

        jLabelTinhTrang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelTinhTrang.setText("TÌNH TRẠNG:");

        jLabelGhiChu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelGhiChu.setText("GHI CHÚ:");

        jButtonThanhToan.setText("Thanh toán");

        jLabelDataDuNo.setText("jLabel1");

        jLabelDataSoTien.setText("jLabel1");

        jLabelDataTongTien.setText("jLabel1");

        jLabelDataTinhTrang.setText("jLabel1");

        jLabelDataGhiChu.setText("jLabel1");

        jLabelDataNgayLapHD.setText("jLabel2");

        jLabelDataCH.setText("jLabel2");

        jLabelDataTenKH.setText("jLabel2");

        jLabelDataNgayGui.setText("jLabel2");

        jLabelDataThanhToan.setText("jLabel2");

        javax.swing.GroupLayout jPanelContainerHoaDonChuaThanhToanLayout = new javax.swing.GroupLayout(jPanelContainerHoaDonChuaThanhToan);
        jPanelContainerHoaDonChuaThanhToan.setLayout(jPanelContainerHoaDonChuaThanhToanLayout);
        jPanelContainerHoaDonChuaThanhToanLayout.setHorizontalGroup(
            jPanelContainerHoaDonChuaThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContainerHoaDonChuaThanhToanLayout.createSequentialGroup()
                .addGroup(jPanelContainerHoaDonChuaThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelContainerHoaDonChuaThanhToanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane7))
                    .addGroup(jPanelContainerHoaDonChuaThanhToanLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanelContainerHoaDonChuaThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelContainerHoaDonChuaThanhToanLayout.createSequentialGroup()
                                .addComponent(jLabelNgayLap)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelDataNgayLapHD, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelContainerHoaDonChuaThanhToanLayout.createSequentialGroup()
                                .addGroup(jPanelContainerHoaDonChuaThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTenKhachHang)
                                    .addComponent(jLabelCanHo))
                                .addGap(31, 31, 31)
                                .addGroup(jPanelContainerHoaDonChuaThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelDataCH, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelDataTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(jPanelContainerHoaDonChuaThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanelContainerHoaDonChuaThanhToanLayout.createSequentialGroup()
                                        .addComponent(jLabelNgayGui)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelDataNgayGui, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelContainerHoaDonChuaThanhToanLayout.createSequentialGroup()
                                        .addComponent(jLabelMaTT)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelDataThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabelTenHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(jPanelContainerHoaDonChuaThanhToanLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanelContainerHoaDonChuaThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDuNo)
                    .addComponent(jLabelGhiChu)
                    .addComponent(jLabelTinhTrang)
                    .addComponent(jLabelTongTien)
                    .addComponent(jLabelSoTienPhaiDong))
                .addGap(27, 27, 27)
                .addGroup(jPanelContainerHoaDonChuaThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelDataDuNo, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addComponent(jLabelDataSoTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDataTongTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDataTinhTrang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDataGhiChu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContainerHoaDonChuaThanhToanLayout.createSequentialGroup()
                .addContainerGap(632, Short.MAX_VALUE)
                .addComponent(jButtonThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );
        jPanelContainerHoaDonChuaThanhToanLayout.setVerticalGroup(
            jPanelContainerHoaDonChuaThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContainerHoaDonChuaThanhToanLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabelTenHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelContainerHoaDonChuaThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTenKhachHang)
                    .addComponent(jLabelNgayGui)
                    .addComponent(jLabelDataTenKH)
                    .addComponent(jLabelDataNgayGui))
                .addGap(18, 18, 18)
                .addGroup(jPanelContainerHoaDonChuaThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCanHo)
                    .addComponent(jLabelMaTT)
                    .addComponent(jLabelDataCH)
                    .addComponent(jLabelDataThanhToan))
                .addGap(18, 18, 18)
                .addGroup(jPanelContainerHoaDonChuaThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNgayLap)
                    .addComponent(jLabelDataNgayLapHD))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanelContainerHoaDonChuaThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDuNo)
                    .addComponent(jLabelDataDuNo))
                .addGap(18, 18, 18)
                .addGroup(jPanelContainerHoaDonChuaThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSoTienPhaiDong)
                    .addComponent(jLabelDataSoTien))
                .addGap(18, 18, 18)
                .addGroup(jPanelContainerHoaDonChuaThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTongTien)
                    .addComponent(jLabelDataTongTien))
                .addGap(18, 18, 18)
                .addGroup(jPanelContainerHoaDonChuaThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTinhTrang)
                    .addComponent(jLabelDataTinhTrang))
                .addGap(18, 18, 18)
                .addGroup(jPanelContainerHoaDonChuaThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGhiChu)
                    .addComponent(jLabelDataGhiChu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jComboBoxCanHoHD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CH1", "CH2", "CH3" }));
        jComboBoxCanHoHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCanHoHDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelHoaDonLayout = new javax.swing.GroupLayout(jPanelHoaDon);
        jPanelHoaDon.setLayout(jPanelHoaDonLayout);
        jPanelHoaDonLayout.setHorizontalGroup(
            jPanelHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelContainerHoaDonChuaThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanelHoaDonLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jComboBoxCanHoHD, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelHoaDonLayout.setVerticalGroup(
            jPanelHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHoaDonLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jComboBoxCanHoHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelContainerHoaDonChuaThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPaneMenuCSH.addTab("Hóa đơn chưa thanh toán", jPanelHoaDon);

        jTableLichSuThuPhi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên khách hàng", "Tên hóa đơn", "Ngày lập", "Ngày đóng", "Tình trạng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTableLichSuThuPhi);
        if (jTableLichSuThuPhi.getColumnModel().getColumnCount() > 0) {
            jTableLichSuThuPhi.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTableLichSuThuPhi.getColumnModel().getColumn(1).setPreferredWidth(150);
            jTableLichSuThuPhi.getColumnModel().getColumn(2).setPreferredWidth(80);
            jTableLichSuThuPhi.getColumnModel().getColumn(3).setPreferredWidth(70);
            jTableLichSuThuPhi.getColumnModel().getColumn(4).setPreferredWidth(70);
            jTableLichSuThuPhi.getColumnModel().getColumn(5).setPreferredWidth(50);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelLichSuThuPhiLayout = new javax.swing.GroupLayout(jPanelLichSuThuPhi);
        jPanelLichSuThuPhi.setLayout(jPanelLichSuThuPhiLayout);
        jPanelLichSuThuPhiLayout.setHorizontalGroup(
            jPanelLichSuThuPhiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLichSuThuPhiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelLichSuThuPhiLayout.setVerticalGroup(
            jPanelLichSuThuPhiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLichSuThuPhiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(348, Short.MAX_VALUE))
        );

        jTabbedPaneMenuCSH.addTab("Lịch sử đóng phí", jPanelLichSuThuPhi);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Thông tin cư dân:");

        jLabelMaCSH.setText("Mã Cư dân:");

        jLabelHoTen.setText("Họ tên:");

        jLabelSDT.setText("SDT:");

        jLabelPhai.setText("Phai:");

        jLabelNgaySinh.setText("Ngày sinh:");

        jLabelCCCD.setText("CCCD:");

        jLabelDataMaCSH.setText("jLabel2");

        jLabelDataSDT.setText("jLabel2");

        jLabelDataPhai.setText("jLabel2");

        jLabelDataNgaysinh.setText("jLabel2");

        jLabelDataCCCD.setText("jLabel2");

        jLabelDataHoten.setText("jLabel2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelPhai, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMaCSH, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDataMaCSH, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDataNgaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDataCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDataPhai, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDataSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDataHoten, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMaCSH)
                    .addComponent(jLabelDataMaCSH))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHoTen)
                    .addComponent(jLabelDataHoten))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSDT)
                    .addComponent(jLabelDataSDT))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPhai)
                    .addComponent(jLabelDataPhai))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNgaySinh)
                    .addComponent(jLabelDataNgaysinh))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCCCD)
                    .addComponent(jLabelDataCCCD))
                .addContainerGap(360, Short.MAX_VALUE))
        );

        jTabbedPaneMenuCSH.addTab("Thông tin người dùng", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(jLabelCSH)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jTabbedPaneMenuCSH)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabelCSH)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPaneMenuCSH, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void TTCanHo() {
        try {
            DefaultTableModel table;
            table = (DefaultTableModel) jTableTTCanHo.getModel();
            String query = "select CAN_HO.ma_can_ho,CHU_SO_HUU.ho_ten,CAN_HO.ma_can_ho,CAN_HO.dien_tich,CAN_HO.khu,CAN_HO.tang from CAN_HO\n" +
            "join CHU_SO_HUU on CAN_HO.ma_chu_so_huu = CHU_SO_HUU.ma_chu_so_huu\n" +
            "where CAN_HO.ma_can_ho = 'CH1'";
            Vector v;
            Statement st = con.createStatement();
            ResultSet rel = st.executeQuery(query);
             
            while (rel.next()) {
                String maCH = rel.getString("ma_can_ho");
                String CSH = rel.getString("ho_ten");
                String dientich = rel.getString("dien_tich");
                String khu = rel.getString("khu");
                String tang = rel.getString("tang");

                jLabelDataMaCH.setText(maCH);
                jLabelDataCSH.setText(CSH);
                jLabelDataDienTich.setText(dientich);
                jLabelDataKhu.setText(khu);
                jLabelDataTang.setText(tang);
                
                v = new Vector();
                v.add(maCH);
                v.add(CSH);
                v.add(dientich);
                v.add(khu);
                v.add(tang);
                table.addRow(v);
            }
            
            jTableTTCanHo.setModel(table);
        } catch (SQLException ex) {
            Logger.getLogger(CHU_SO_HUU.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void TTDichVu() {
            DefaultTableModel table;
            table = (DefaultTableModel) jTableTTDichVu.getModel();
            String query = "select * from DICH_VU";
            Vector v;
            try {
                Statement st = con.createStatement();
                ResultSet rel = st.executeQuery(query);

                while (rel.next()) {
                    String maDV = rel.getString("ma_dich_vu");
                    String TenDV = rel.getString("ten_dich_vu");
                    String Thue = rel.getString("vat");
                    String DonGiga = rel.getString("don_gia");
                    String DonVi = rel.getString("don_vi");

                    v = new Vector();
                    v.add(maDV);
                    v.add(TenDV);
                    v.add(Thue);
                    v.add(DonGiga);
                    v.add(DonVi);

                    table.addRow(v);
                }
                st.close();
                rel.close();
        } catch (SQLException sQLException) {
        }
    }
    
    private void TTHoaDon() {
        try {
            // chuan bi du lieu
            Statement st = con.createStatement();
            String query_LabelHoadon = "select HOA_DON.ten_hoa_don,CHU_SO_HUU.ho_ten,HOA_DON.ma_can_ho,HOA_DON.ngay_tao,HOA_DON.tien_no, HOA_DON.tien_thang from HOA_DON\n" +
            "join CAN_HO on HOA_DON.ma_can_ho = CAN_HO.ma_can_ho\n" +
            "join CHU_SO_HUU on CHU_SO_HUU.ma_chu_so_huu = CAN_HO.ma_chu_so_huu\n" +
            "where CAN_HO.ma_can_ho = 'CH1' and HOA_DON.ngay_dong_tien is null;";
            
            
            // chon du lieu
            DefaultComboBoxModel comboBoxModel = (DefaultComboBoxModel) jComboBoxCanHoHD.getModel();

            ResultSet relLabelHoadon = st.executeQuery(query_LabelHoadon);
            //do du lieu thong tin
            
            while (relLabelHoadon.next()) {

                String maHD = relLabelHoadon.getString("ma_hoa_don");
                String tenHD = relLabelHoadon.getString("ten_hoa_don");
                String TenCSH = relLabelHoadon.getString("ho_ten");
                String maCH = relLabelHoadon.getString("ma_can_ho");
                String ngaytao = relLabelHoadon.getString("ngay_tao");
                String tienno = relLabelHoadon.getString("tien_no");
                String tienthang = relLabelHoadon.getString("tien_thang"); 
                String maNV = relLabelHoadon.getString("ma_nhan_vien"); 
                
                jLabelTenHoaDon.setText("Hoa don thang "+tenHD);
                jLabelDataTenKH.setText(TenCSH);
                jLabelDataCH.setText(maCH);
                jLabelDataNgayLapHD.setText(ngaytao);
                jLabelDataDuNo.setText(tienno);
                jLabelDataSoTien.setText(tienthang);
                
                int tongtien = Integer.parseInt(tienthang) + Integer.parseInt(tienno);
                jLabelDataTongTien.setText(String.valueOf(tongtien));
            }
            
            // do du lieu len bang dich vu
            String query_Table = "select DICH_VU.ten_dich_vu,DICH_VU_CAN_HO.ngay_bat_dau,DICH_VU_CAN_HO.ngay_ket_thuc,DICH_VU_CAN_HO.so_luong,DICH_VU.don_gia,DICH_VU.don_vi,DICH_VU.vat from DICH_VU\n" +
            "join DICH_VU_CAN_HO on DICH_VU.ma_dich_vu = DICH_VU_CAN_HO.ma_dich_vu\n" +
            "where DICH_VU_CAN_HO.ma_can_ho = '%s';";
            
            String query_table = String.format(query_Table, "CH1");
            DefaultTableModel tableHoaDon = (DefaultTableModel) jTableHoaDon.getModel();
            
            ResultSet rel2 = st.executeQuery(query_Table);
            Vector row;
            int stt = 1;
            while (rel2.next()) {
                row = new Vector();
                row.add(stt);
                row.add(rel2.getString("ten_dich_vu"));
                row.add(rel2.getString("ngay_bat_dau"));
                row.add(rel2.getString("ngay_ket_thuc"));
                row.add(rel2.getString("so_luong"));
                row.add(rel2.getString("don_gia"));
                row.add(rel2.getString("don_vi"));
                row.add(rel2.getString("vat"));
                
                int dongia = rel2.getInt("don_gia");
                int soluong = rel2.getInt("so_luong");
                int thue = rel2.getInt("vat");
                
                int thanhtien = (int) (dongia*soluong*thue/100);
                row.add(thanhtien);
                tableHoaDon.addRow(row);
                stt++;
            }
            
            // do du lieu duoi bang

                jLabelDataNgayGui.setText(java.time.LocalDate.now().toString());
                jLabelDataThanhToan.setText("Ngan hang chung cu");
                jLabelDataTinhTrang.setText("chua dong");
                jLabelDataGhiChu.setText("Vui long thanh toan hoa hon tre nhat sau 15 ngay ke tu ngay lap hoa don");
         
        } catch (SQLException sQLException) {
        }
        
    }
    
    private void TTLichSuThuPhi () {
        DefaultTableModel table = (DefaultTableModel) jTableLichSuThuPhi.getModel();
        String query = "select CHU_SO_HUU.ho_ten,HOA_DON.ten_hoa_don,HOA_DON.ngay_tao,HOA_DON.ngay_dong_tien from HOA_DON\n" +
        "join CAN_HO on HOA_DON.ma_can_ho = CAN_HO.ma_can_ho\n" +
        "join CHU_SO_HUU on CAN_HO.ma_chu_so_huu = CHU_SO_HUU.ma_chu_so_huu\n" +
        "where CAN_HO.ma_can_ho = 'CH1' and HOA_DON.ngay_dong_tien IS NOT NULL";
            
        try {
            Statement st = con.createStatement();
            ResultSet rel = st.executeQuery(query);
            int i = 1;
            Vector row ;
            while (rel.next()) {
                row = new Vector();
                String tenKH = rel.getString("ho_ten");
                String tenHD = rel.getString("ten_hoa_don");
                String ngaylap = rel.getString("ngay_tao");
                String ngaydong = rel.getString("ngay_dong_tien");
                
                row.add(i);
                row.add(tenKH);
                row.add(tenHD);
                row.add(ngaylap);
                row.add(ngaydong);
                row.add("Da dong");
                row.add("Khong");
               
                table.addRow(row);
                i++;
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    private void TTCuDan() {
        String query = "select CHU_SO_HUU.ma_chu_so_huu,ho_ten,sdt,phai,ngay_sinh,cccd from CHU_SO_HUU\n" +
        "join CAN_HO on CAN_HO.ma_chu_so_huu = CHU_SO_HUU.ma_chu_so_huu\n" +
        "where CAN_HO.ma_can_ho = 'CH1'";
        
        try {
            Statement st = con.createStatement();
            ResultSet rel = st.executeQuery(query);
            
            while (rel.next()) {
                jLabelDataMaCSH.setText(rel.getString("ma_chu_so_huu"));
                jLabelDataHoten.setText(rel.getString("ho_ten"));
                jLabelDataSDT.setText(rel.getString("sdt"));
                jLabelDataPhai.setText(rel.getString("phai"));
                jLabelDataNgaysinh.setText(rel.getString("ngay_sinh"));
                jLabelDataCCCD.setText(rel.getString("cccd"));
            }
            
            
        } catch (SQLException sQLException) {
        }
    }
    
//    public static String ConvertDecimalToString(DecimalStyle number)
//    {
//        String s = number.ToString("#");
//        String[] so = new String[] { "không", "một", "hai", "ba", "bốn", "năm", "sáu", "bảy", "tám", "chín" };
//        String[] hang = new String[] { "", "nghìn", "triệu", "tỷ" };
//        int i, j, donvi, chuc, tram;
//        String str = " ";
//        boolean booAm = false;
//        decimal decS = 0;
//        //Tung addnew
//        try
//        {
//            decS = Convert.ToDecimal(s.ToString());
//        }
//        catch
//        {
//        }
//        if (decS < 0)
//        {
//            decS = -decS;
//            s = decS.ToString();
//            booAm = true;
//        }
//        i = s.Length;
//        if (i == 0)
//            str = so[0] + str;
//        else
//        {
//            j = 0;
//            while (i > 0)
//            {
//                donvi = ConvertToInt32(s.Substring(i - 1, 1));
//                i--;
//                if (i > 0)
//                    chuc = Convert.ToInt32(s.Substring(i - 1, 1));
//                else
//                    chuc = -1;
//                i--;
//                if (i > 0)
//                    tram = Convert.ToInt32(s.Substring(i - 1, 1));
//                else
//                    tram = -1;
//                i--;
//                if ((donvi > 0) || (chuc > 0) || (tram > 0) || (j == 3))
//                    str = hang[j] + str;
//                j++;
//                if (j > 3) j = 1;
//                if ((donvi == 1) && (chuc > 1))
//                    str = "một " + str;
//                else
//                {
//                    if ((donvi == 5) && (chuc > 0))
//                        str = "lăm " + str;
//                    else if (donvi > 0)
//                        str = so[donvi] + " " + str;
//                }
//                if (chuc < 0)
//                    break;
//                else
//                {
//                    if ((chuc == 0) && (donvi > 0)) str = "lẻ " + str;
//                    if (chuc == 1) str = "mười " + str;
//                    if (chuc > 1) str = so[chuc] + " mươi " + str;
//                }
//                if (tram < 0) break;
//                else
//                {
//                    if ((tram > 0) || (chuc > 0) || (donvi > 0)) str = so[tram] + " trăm " + str;
//                }
//                str = " " + str;
//            }
//        }
//        if (booAm) str = "Âm " + str;
//        return str + "đồng chẵn";
//    }
    
    private void jButtonXoaTatCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXoaTatCaActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTableDichVuDaChon.getModel();
        int row = jTableDichVuDaChon.getRowCount();
        if (row == 0) {
            JFrame frame = new JFrame("JOptionPane showMessageDialog example");
            JOptionPane.showMessageDialog(frame,
                    "Hay chon dich vu can xoa",
                    "Chua co du lieu",
                    JOptionPane.ERROR_MESSAGE);
        } else 
        model.setRowCount(0);
    }//GEN-LAST:event_jButtonXoaTatCaActionPerformed

    private void jTableTTDichVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTTDichVuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableTTDichVuMouseClicked

    private void jButtonThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemActionPerformed
        // TODO add your handling code here:
        
        TableModel model = jTableTTDichVu.getModel();
        int[] index = jTableTTDichVu.getSelectedRows();
        DefaultTableModel table = (DefaultTableModel) jTableDichVuDaChon.getModel();
        Object[] row = new Object[5];
            
        try {
            if (index.length == 0) {
                JFrame frame = new JFrame("JOptionPane showMessageDialog example");
                JOptionPane.showMessageDialog(frame,
                        "Hay chon dich vu can them",
                        "Khong the them",
                        JOptionPane.ERROR_MESSAGE);
            } else {
                for (int i = 0; i<index.length; i++) {
                row[0] = model.getValueAt(index[i], 0);
                row[1] = model.getValueAt(index[i], 1);
                row[2] = model.getValueAt(index[i], 2);
                row[3] = model.getValueAt(index[i], 3);
                row[4] = model.getValueAt(index[i], 4);

                table.addRow(row);
            }
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonThemActionPerformed

    private void jButtonDangKiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDangKiActionPerformed
        // TODO add your handling code here:
        try {
            Statement st;
            ArrayList<String> query_insert;
            query_insert = new ArrayList<String>();
            String thongbao = "";
            int index = jTableDichVuDaChon.getRowCount();
            DefaultTableModel model = (DefaultTableModel) jTableDichVuDaChon.getModel();

            for (int i = 0; i < index; i++) {
                st = con.createStatement();
                String query = "insert into DICH_VU_CAN_HO (ma_dich_vu,ma_can_ho,ngay_bat_dau,so_luong) \n" +
                "values ('%s','CH1','%s','%s')";

                String maDV = model.getValueAt(i, 0).toString();
                String tenDV = model.getValueAt(i, 1).toString();
                String soluong = model.getValueAt(i, 5).toString();
                String date = java.time.LocalDate.now().toString();
                
                thongbao += String.format("Thong tin dich vu: %s, so luong: %s \n", tenDV, soluong);
                
                query = String.format(query, maDV, soluong, date);
                query_insert.set(i, query);
            }

            JFrame frame = new JFrame("JOptionPane showMessageDialog example");
            JOptionPane.showMessageDialog(frame,
            thongbao,
            "Thông báo đăng kí",
            JOptionPane.INFORMATION_MESSAGE);
            
            
        } catch (SQLException sQLException) {
            sQLException.printStackTrace();
        }
    }//GEN-LAST:event_jButtonDangKiActionPerformed

    private void jButtonXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXoaActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTableDichVuDaChon.getModel();
        try {
            int row = jTableDichVuDaChon.getSelectedRow();
            if (row == -1) {
                JFrame frame = new JFrame("JOptionPane showMessageDialog example");
                JOptionPane.showMessageDialog(frame,
                        "Hay chon dich vu can xoa",
                        "Khong the xoa",
                        JOptionPane.ERROR_MESSAGE);
            } else 
            model.removeRow(row);
        } catch (HeadlessException headlessException) {
        }
        
    }//GEN-LAST:event_jButtonXoaActionPerformed

    private void jComboBoxCanHoHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCanHoHDActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBoxCanHoHDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void run_CHU_SO_HUU() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CHU_SO_HUU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CHU_SO_HUU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CHU_SO_HUU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CHU_SO_HUU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDangKi;
    private javax.swing.JButton jButtonThanhToan;
    private javax.swing.JButton jButtonThem;
    private javax.swing.JButton jButtonXoa;
    private javax.swing.JButton jButtonXoaTatCa;
    private javax.swing.JComboBox<String> jComboBoxCanHoHD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCCCD;
    private javax.swing.JLabel jLabelCSH;
    private javax.swing.JLabel jLabelCanHo;
    private javax.swing.JLabel jLabelChu;
    private javax.swing.JLabel jLabelDataCCCD;
    private javax.swing.JLabel jLabelDataCH;
    private javax.swing.JLabel jLabelDataCSH;
    private javax.swing.JLabel jLabelDataDienTich;
    private javax.swing.JLabel jLabelDataDuNo;
    private javax.swing.JLabel jLabelDataGhiChu;
    private javax.swing.JLabel jLabelDataHoten;
    private javax.swing.JLabel jLabelDataKhu;
    private javax.swing.JLabel jLabelDataMaCH;
    private javax.swing.JLabel jLabelDataMaCSH;
    private javax.swing.JLabel jLabelDataNgayGui;
    private javax.swing.JLabel jLabelDataNgayLapHD;
    private javax.swing.JLabel jLabelDataNgaysinh;
    private javax.swing.JLabel jLabelDataPhai;
    private javax.swing.JLabel jLabelDataSDT;
    private javax.swing.JLabel jLabelDataSoTien;
    private javax.swing.JLabel jLabelDataTang;
    private javax.swing.JLabel jLabelDataTenKH;
    private javax.swing.JLabel jLabelDataThanhToan;
    private javax.swing.JLabel jLabelDataTinhTrang;
    private javax.swing.JLabel jLabelDataTongTien;
    private javax.swing.JLabel jLabelDienTich;
    private javax.swing.JLabel jLabelDuNo;
    private javax.swing.JLabel jLabelGhiChu;
    private javax.swing.JLabel jLabelHoTen;
    private javax.swing.JLabel jLabelKhu;
    private javax.swing.JLabel jLabelMaCSH;
    private javax.swing.JLabel jLabelMaCanHo;
    private javax.swing.JLabel jLabelMaTT;
    private javax.swing.JLabel jLabelNgayGui;
    private javax.swing.JLabel jLabelNgayLap;
    private javax.swing.JLabel jLabelNgaySinh;
    private javax.swing.JLabel jLabelPhai;
    private javax.swing.JLabel jLabelSDT;
    private javax.swing.JLabel jLabelSoTienPhaiDong;
    private javax.swing.JLabel jLabelTTDangKi;
    private javax.swing.JLabel jLabelTTDichVu;
    private javax.swing.JLabel jLabelTang;
    private javax.swing.JLabel jLabelTenHoaDon;
    private javax.swing.JLabel jLabelTenKhachHang;
    private javax.swing.JLabel jLabelTinhTrang;
    private javax.swing.JLabel jLabelTongTien;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelContainerHoaDonChuaThanhToan;
    private javax.swing.JPanel jPanelDangKiDichVu;
    private javax.swing.JPanel jPanelHoaDon;
    private javax.swing.JPanel jPanelLichSuThuPhi;
    private javax.swing.JPanel jPanelTTCanHo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPaneMenuCSH;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTableDichVuDaChon;
    private javax.swing.JTable jTableHoaDon;
    private javax.swing.JTable jTableLichSuThuPhi;
    private javax.swing.JTable jTableTTCanHo;
    private javax.swing.JTable jTableTTDichVu;
    // End of variables declaration//GEN-END:variables
}
